### ISSUE TITLE
Loading of .dll files with .toml with Python 3.8

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/imod_coupler#40]
Using the .toml file to provide the paths to the .dll files,
ctypes throws an error when using python 3.8:

```
Traceback (most recent call last):
  File "C:\Users\engelen\Miniconda3\envs\imod6\Scripts\imodc-script.py", line 33, in <module>
    sys.exit(load_entry_point('imod-coupler', 'console_scripts', 'imodc')())
  File "c:\tools\python_packages\imod_coupler\imod_coupler\__main__.py", line 60, in main
    config = Config(config_path, timing)
  File "c:\tools\python_packages\imod_coupler\imod_coupler\config.py", line 34, in __init__
    self.get_kernel_data(kernels, timing)
  File "c:\tools\python_packages\imod_coupler\imod_coupler\config.py", line 80, in get_kernel_data
    self.kernels[kernel] = XmiWrapper(
  File "c:\tools\python_packages\xmipy\xmipy\xmiwrapper.py", line 65, in __init__
    self.lib = CDLL(lib_path, winmode=0x08)
  File "C:\Users\engelen\Miniconda3\envs\imod6\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'c:\Users\engelen\mfmetaswap\MetaSWAP.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

When using python 3.7, however, there is no issue.

Seems to be caused by the changed dll search mechanism in python 3.8:
https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python

**Comment by Hofer-Julian** [comment]
That should be fixed within xmipy.
Is your local xmipy installation up to date?

**Comment by JoerivanEngelen** [comment]
It is on the WCP, there I used the latest developer version

**Comment by Hofer-Julian** [comment]
Annoying, not sure why adding winmode=0x08 fixed it on my machine, but not on yours...

**Comment by Hofer-Julian** [comment]
Tested it with @JoerivanEngelen, not reproducable on local machine
